openapi: 3.1.0
info:
  title: cademi
  version: '1.0'
  summary: Cademí
  description: ''
  license:
    name: 'Contrato de Licença de Uso - '
    url: 'https://compliance.cademi.com.br/contrato-de-licenca-de-uso'
servers:
  - url: 'https://<sua-cademi>.cademi.com.br/api/v1'
    description: production
paths:
  '/usuario/lista_por_tag/{tag_id}':
    parameters:
      - schema:
          type: string
        name: tag_id
        in: path
        required: true
        description: ID da TAG
    get:
      summary: Listar usuários por tag
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '200':
                  value:
                    success: true
                    code: 200
                    data:
                      paginator:
                        perPage: 150
                        next_page_url: 'http://membros.dvp/api/v1/usuario/lista_por_tag/1?cursor=eyJ1c3Vhcmlvcy5pZCI6MTY0MzMyLCJfcG9pbnRzVG9OZXh0SXRlbXMiOnRydWV9'
                        prev_page_url: null
                      usuario:
                        - id: 1051
                          nome: Joana C
                          email: teste@oculto.com.br
                          celular: null
                          login_auto: 'http://membros.dvp/auth/login?crstk='
                          criado_em: '2020-01-12 19:59:20'
                          ultimo_acesso_em: null
                        - id: 1060
                          nome: Gilson D
                          email: teste@oculto.com.br
                          celular: null
                          login_auto: 'http://membros.dvp/auth/login?crstk='
                          criado_em: '2020-01-20 15:22:56'
                          ultimo_acesso_em: '2020-01-20 15:34:57'
                        - id: 14904
                          nome: Márcio B
                          email: teste@oculto.com.br
                          celular: null
                          login_auto: 'http://membros.dvp/auth/login?crstk='
                          criado_em: '2020-04-12 15:02:02'
                          ultimo_acesso_em: '2020-06-22 15:13:39'
                    profiler:
                      start: 1646237242.936336
                      finish: 1646237243.014636
                      process: 0.07829999923706055
      operationId: get-usuario-lista_por_tag-tag_id
      description: Retorna uma lista de usuários à partir da ID de uma determinada TAG
components:
  schemas: {}
  securitySchemes:
    Sua API Key:
      type: http
      scheme: bearer
      description: Sua chave de API
security:
  - Authorization: []
